version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/tamilapp

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/set_permissions.sh
      runas: root
  # The migrate_db.sh line is now REMOVED
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root