version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/tamilapp

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    # This script sets ownership for all deployed files, including the new db file.
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root