// <auto-generated />
using System;
using ICEDT_TamilApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICEDT_TamilApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728050937_CorrectLessonUniqueConstraint")]
    partial class CorrectLessonUniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MainActivityId");

                    b.HasIndex("SequenceOrder")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId");

                    b.HasIndex("LevelId", "SequenceOrder")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("LevelId");

                    b.HasIndex("SequenceOrder")
                        .IsUnique();

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.MainActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MainActivities");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.UserCurrentProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLessonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCurrentProgressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("CurrentLessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("UserCurrentProgress");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.UserProgress", b =>
                {
                    b.Property<long>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgressId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Activity", b =>
                {
                    b.HasOne("ICEDT_TamilApp.Domain.Entities.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.MainActivity", null)
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Activities")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.MainActivity", "MainActivity")
                        .WithMany()
                        .HasForeignKey("MainActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Lesson");

                    b.Navigation("MainActivity");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("ICEDT_TamilApp.Domain.Entities.Level", "Level")
                        .WithMany("Lessons")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.UserCurrentProgress", b =>
                {
                    b.HasOne("ICEDT_TamilApp.Domain.Entities.Lesson", "CurrentLesson")
                        .WithMany()
                        .HasForeignKey("CurrentLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.Lesson", null)
                        .WithMany("UserCurrentProgress")
                        .HasForeignKey("LessonId");

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.User", "User")
                        .WithOne("UserCurrentProgress")
                        .HasForeignKey("ICEDT_TamilApp.Domain.Entities.UserCurrentProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("ICEDT_TamilApp.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICEDT_TamilApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("UserCurrentProgress");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.Level", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.MainActivity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ICEDT_TamilApp.Domain.Entities.User", b =>
                {
                    b.Navigation("UserCurrentProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
