name: Deploy to Staging EC2

on:
  push:
    branches:
      - staging # This pipeline runs when you push to the 'staging' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Use your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish src/ICEDT_TamilApp.Web/ICEDT_TamilApp.Web.csproj -c Release -o ./publish --runtime linux-x64 --self-contained false

    - name: Generate deployment package
      run: |
        mkdir -p deployment_package
        cp -r ./publish/* ./deployment_package/
        cp appspec.yml ./deployment_package/
        cp -r scripts ./deployment_package/
        cd deployment_package
        zip -r ../deployment.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Your AWS region

    - name: Upload to S3
      run: aws s3 cp deployment.zip s3://icedt-tamilapp-deployments/deployment.zip # Use your bucket name

    - name: Deploy to EC2 with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ICEDT-TamilApp-API \
          --deployment-group-name Staging-Group \
          --s3-location bucket=icedt-tamilapp-deployments,key=deployment.zip,bundleType=zip